//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoHanh
    {
        public BaoHanh()
        {
            this.YeuCauBHs = new HashSet<YeuCauBH>();
        }
    
        public int MaBH { get; set; }
        public Nullable<int> MaDDH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> NgayDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> SDT { get; set; }
        public string NoiDungBH { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual DDH DDH { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual ICollection<YeuCauBH> YeuCauBHs { get; set; }
    }
}
