//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTDiaChi
    {
        public int MaCTDiaChi { get; set; }
        public Nullable<int> MaDiaChi { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số nhà.")]
        public string SoNha { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên đường.")]
        public string TenDuong { get; set; }
        public string PhuongXa { get; set; }
        public string QuanHuyen { get; set; }
        public string TinhThanh { get; set; }
        public Nullable<int> MacDinh { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên người nhận.")]
        public string TenNguoiNhan { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập sdt người nhận.")]
        public string SDTNguoiNhan { get; set; }
    
        public virtual DiaChi DiaChi { get; set; }
    }
}
