//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDH
    {
        public DDH()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.CTDDHs = new HashSet<CTDDH>();
            this.HoanHangs = new HashSet<HoanHang>();
            this.HuyHangs = new HashSet<HuyHang>();
        }
    
        public int MaDDH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string MaGiamGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string SDTNguoiNhan { get; set; }
        public Nullable<int> MaNVC { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SoNha { get; set; }
        public string TenDuong { get; set; }
        public string PhuongXa { get; set; }
        public string QuanHuyen { get; set; }
        public string TinhThanh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual ICollection<CTDDH> CTDDHs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual MaGiamGia MaGiamGia1 { get; set; }
        public virtual NhaVanChuyen NhaVanChuyen { get; set; }
        public virtual ICollection<HoanHang> HoanHangs { get; set; }
        public virtual ICollection<HuyHang> HuyHangs { get; set; }
    }
}
