//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public DiaChi()
        {
            this.CTDiaChis = new HashSet<CTDiaChi>();
        }
    
        public int MaDiaChi { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual ICollection<CTDiaChi> CTDiaChis { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
