//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public GioHang()
        {
            this.CTGioHangs = new HashSet<CTGioHang>();
        }
    
        public int MaGioHang { get; set; }
        public Nullable<decimal> TongTienGioHang { get; set; }
        public Nullable<int> MaKH { get; set; }
    
        public virtual ICollection<CTGioHang> CTGioHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
