//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuyHang
    {
        public int MaHuyDon { get; set; }
        public Nullable<int> MaDDH { get; set; }
        public Nullable<int> MaKH { get; set; }
        public string LyDonHuy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
    
        public virtual DDH DDH { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
