//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public MaGiamGia()
        {
            this.DDHs = new HashSet<DDH>();
            this.MaGiamGia_KhachHang = new HashSet<MaGiamGia_KhachHang>();
        }
    
        public string MaGiamGia1 { get; set; }
        public string TenMGG { get; set; }
        public Nullable<int> SLDaSuDung { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> TiLeGiam { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<DDH> DDHs { get; set; }
        public virtual ICollection<MaGiamGia_KhachHang> MaGiamGia_KhachHang { get; set; }
    }
}
