//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia_KhachHang
    {
        public int ID { get; set; }
        public string MaGiamGia { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual MaGiamGia MaGiamGia1 { get; set; }
    }
}
