//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ThietBiDienTuEntities1 : DbContext
    {
        public ThietBiDienTuEntities1()
            : base("name=ThietBiDienTuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaoHanh> BaoHanhs { get; set; }
        public DbSet<CTDDH> CTDDHs { get; set; }
        public DbSet<CTDiaChi> CTDiaChis { get; set; }
        public DbSet<CTGioHang> CTGioHangs { get; set; }
        public DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public DbSet<DanhMuc> DanhMucs { get; set; }
        public DbSet<DDH> DDHs { get; set; }
        public DbSet<DiaChi> DiaChis { get; set; }
        public DbSet<GioHang> GioHangs { get; set; }
        public DbSet<HangSanXuat> HangSanXuats { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<HoanHang> HoanHangs { get; set; }
        public DbSet<HuyHang> HuyHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<MaGiamGia> MaGiamGias { get; set; }
        public DbSet<MaGiamGia_KhachHang> MaGiamGia_KhachHang { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<NhaVanChuyen> NhaVanChuyens { get; set; }
        public DbSet<Quyen> Quyens { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<YeuCauBH> YeuCauBHs { get; set; }
    
        public virtual int AddToCart(Nullable<int> customerId, Nullable<int> productId, Nullable<int> quantity)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("Quantity", quantity) :
                new ObjectParameter("Quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddToCart", customerIdParameter, productIdParameter, quantityParameter);
        }
    
        public virtual int CapNhatGHThanhCong(Nullable<int> maDDH)
        {
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatGHThanhCong", maDDHParameter);
        }
    
        public virtual int CapNhatGiaoHang(Nullable<int> maDDH)
        {
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatGiaoHang", maDDHParameter);
        }
    
        public virtual int CapNhatHuyDonHang(Nullable<int> maKH, Nullable<int> maDDH, string lyDo)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatHuyDonHang", maKHParameter, maDDHParameter, lyDoParameter);
        }
    
        public virtual int CapNhatHuyDonHangByMaDDH(Nullable<int> maDDH, string lyDo)
        {
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatHuyDonHangByMaDDH", maDDHParameter, lyDoParameter);
        }
    
        public virtual int CreateOrderFromCart(Nullable<int> customerId, string maGiamGia, Nullable<int> maNVC, string houseNumber, string streetName, string ward, string district, string province, string userRc, string phoneNo, string ghiChu)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var maGiamGiaParameter = maGiamGia != null ?
                new ObjectParameter("MaGiamGia", maGiamGia) :
                new ObjectParameter("MaGiamGia", typeof(string));
    
            var maNVCParameter = maNVC.HasValue ?
                new ObjectParameter("MaNVC", maNVC) :
                new ObjectParameter("MaNVC", typeof(int));
    
            var houseNumberParameter = houseNumber != null ?
                new ObjectParameter("HouseNumber", houseNumber) :
                new ObjectParameter("HouseNumber", typeof(string));
    
            var streetNameParameter = streetName != null ?
                new ObjectParameter("StreetName", streetName) :
                new ObjectParameter("StreetName", typeof(string));
    
            var wardParameter = ward != null ?
                new ObjectParameter("Ward", ward) :
                new ObjectParameter("Ward", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("District", district) :
                new ObjectParameter("District", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("Province", province) :
                new ObjectParameter("Province", typeof(string));
    
            var userRcParameter = userRc != null ?
                new ObjectParameter("UserRc", userRc) :
                new ObjectParameter("UserRc", typeof(string));
    
            var phoneNoParameter = phoneNo != null ?
                new ObjectParameter("PhoneNo", phoneNo) :
                new ObjectParameter("PhoneNo", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateOrderFromCart", customerIdParameter, maGiamGiaParameter, maNVCParameter, houseNumberParameter, streetNameParameter, wardParameter, districtParameter, provinceParameter, userRcParameter, phoneNoParameter, ghiChuParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> danhGia(Nullable<int> maKH, Nullable<int> maSP, string noiDung, Nullable<int> soSao)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var soSaoParameter = soSao.HasValue ?
                new ObjectParameter("SoSao", soSao) :
                new ObjectParameter("SoSao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("danhGia", maKHParameter, maSPParameter, noiDungParameter, soSaoParameter);
        }
    
        public virtual ObjectResult<GetCartItems_Result> GetCartItems(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCartItems_Result>("GetCartItems", customerIdParameter);
        }
    
        public virtual ObjectResult<GetCustomerAddress_Result> GetCustomerAddress(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustomerAddress_Result>("GetCustomerAddress", customerIdParameter);
        }
    
        public virtual ObjectResult<GetDanhGia1_Result> GetDanhGia1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDanhGia1_Result>("GetDanhGia1");
        }
    
        public virtual ObjectResult<GetDanhGia2_Result> GetDanhGia2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDanhGia2_Result>("GetDanhGia2");
        }
    
        public virtual ObjectResult<GetDanhGia3_Result> GetDanhGia3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDanhGia3_Result>("GetDanhGia3");
        }
    
        public virtual ObjectResult<GetHoanHangByMaKH_Result> GetHoanHangByMaKH(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetHoanHangByMaKH_Result>("GetHoanHangByMaKH", maKHParameter);
        }
    
        public virtual ObjectResult<GetMaGiamGiaInfoForKhachHang_Result> GetMaGiamGiaInfoForKhachHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMaGiamGiaInfoForKhachHang_Result>("GetMaGiamGiaInfoForKhachHang", maKHParameter);
        }
    
        public virtual ObjectResult<GetMaGiamGiaInfoForKhachHangAndTrangThai_Result> GetMaGiamGiaInfoForKhachHangAndTrangThai(Nullable<int> maKH, Nullable<int> trangThai)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMaGiamGiaInfoForKhachHangAndTrangThai_Result>("GetMaGiamGiaInfoForKhachHangAndTrangThai", maKHParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByCustomerId_Result> GetOrderInfoByCustomerId(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByCustomerId_Result>("GetOrderInfoByCustomerId", maKHParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByCustomerIdAndOrderIDAndStatus_Result> GetOrderInfoByCustomerIdAndOrderIDAndStatus(Nullable<int> maKH, Nullable<int> maDDH, Nullable<int> trangThai)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByCustomerIdAndOrderIDAndStatus_Result>("GetOrderInfoByCustomerIdAndOrderIDAndStatus", maKHParameter, maDDHParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByCustomerIdAndStatus_Result> GetOrderInfoByCustomerIdAndStatus(Nullable<int> maKH, Nullable<int> trangThai)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByCustomerIdAndStatus_Result>("GetOrderInfoByCustomerIdAndStatus", maKHParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByMaDDH_Result> GetOrderInfoByMaDDH(Nullable<int> maDDH)
        {
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByMaDDH_Result>("GetOrderInfoByMaDDH", maDDHParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByMaHoanHang_Result> GetOrderInfoByMaHoanHang(Nullable<int> maHoanHang)
        {
            var maHoanHangParameter = maHoanHang.HasValue ?
                new ObjectParameter("MaHoanHang", maHoanHang) :
                new ObjectParameter("MaHoanHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByMaHoanHang_Result>("GetOrderInfoByMaHoanHang", maHoanHangParameter);
        }
    
        public virtual ObjectResult<GetOrderInfoByStatus1_Result> GetOrderInfoByStatus1(Nullable<int> trangThai)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderInfoByStatus1_Result>("GetOrderInfoByStatus1", trangThaiParameter);
        }
    
        public virtual ObjectResult<HienThiHoanHangBangTrangThai_Result> HienThiHoanHangBangTrangThai(Nullable<int> trangThai)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HienThiHoanHangBangTrangThai_Result>("HienThiHoanHangBangTrangThai", trangThaiParameter);
        }
    
        public virtual int InsertCustomerAddress(Nullable<int> customerId, string houseNumber, string streetName, string ward, string district, string province, Nullable<int> isDefault, string userRc, string phoneNo)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var houseNumberParameter = houseNumber != null ?
                new ObjectParameter("HouseNumber", houseNumber) :
                new ObjectParameter("HouseNumber", typeof(string));
    
            var streetNameParameter = streetName != null ?
                new ObjectParameter("StreetName", streetName) :
                new ObjectParameter("StreetName", typeof(string));
    
            var wardParameter = ward != null ?
                new ObjectParameter("Ward", ward) :
                new ObjectParameter("Ward", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("District", district) :
                new ObjectParameter("District", typeof(string));
    
            var provinceParameter = province != null ?
                new ObjectParameter("Province", province) :
                new ObjectParameter("Province", typeof(string));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("IsDefault", isDefault) :
                new ObjectParameter("IsDefault", typeof(int));
    
            var userRcParameter = userRc != null ?
                new ObjectParameter("UserRc", userRc) :
                new ObjectParameter("UserRc", typeof(string));
    
            var phoneNoParameter = phoneNo != null ?
                new ObjectParameter("PhoneNo", phoneNo) :
                new ObjectParameter("PhoneNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertCustomerAddress", customerIdParameter, houseNumberParameter, streetNameParameter, wardParameter, districtParameter, provinceParameter, isDefaultParameter, userRcParameter, phoneNoParameter);
        }
    
        public virtual int InsertHoanTraDonHang(Nullable<int> maDDH, Nullable<int> maKH, string lyDo)
        {
            var maDDHParameter = maDDH.HasValue ?
                new ObjectParameter("MaDDH", maDDH) :
                new ObjectParameter("MaDDH", typeof(int));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHoanTraDonHang", maDDHParameter, maKHParameter, lyDoParameter);
        }
    
        public virtual ObjectResult<layDanhGia_Result> layDanhGia(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<layDanhGia_Result>("layDanhGia", maSPParameter);
        }
    
        public virtual ObjectResult<LayHangBangMaDanhMuc_Result> LayHangBangMaDanhMuc(Nullable<int> maDanhMuc)
        {
            var maDanhMucParameter = maDanhMuc.HasValue ?
                new ObjectParameter("MaDanhMuc", maDanhMuc) :
                new ObjectParameter("MaDanhMuc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayHangBangMaDanhMuc_Result>("LayHangBangMaDanhMuc", maDanhMucParameter);
        }
    
        public virtual int LuuMaGiamGiaForKhachHang(string maGiamGia, Nullable<int> maKH)
        {
            var maGiamGiaParameter = maGiamGia != null ?
                new ObjectParameter("MaGiamGia", maGiamGia) :
                new ObjectParameter("MaGiamGia", typeof(string));
    
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LuuMaGiamGiaForKhachHang", maGiamGiaParameter, maKHParameter);
        }
    
        public virtual int RemoveFromCart(Nullable<int> customerId, Nullable<int> productId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RemoveFromCart", customerIdParameter, productIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_CapNhatTrangThaiBaoHanh(Nullable<int> maPhieuBH, Nullable<int> trangThaiYeuCauBH, Nullable<int> trangThaiBaoHanh)
        {
            var maPhieuBHParameter = maPhieuBH.HasValue ?
                new ObjectParameter("MaPhieuBH", maPhieuBH) :
                new ObjectParameter("MaPhieuBH", typeof(int));
    
            var trangThaiYeuCauBHParameter = trangThaiYeuCauBH.HasValue ?
                new ObjectParameter("TrangThaiYeuCauBH", trangThaiYeuCauBH) :
                new ObjectParameter("TrangThaiYeuCauBH", typeof(int));
    
            var trangThaiBaoHanhParameter = trangThaiBaoHanh.HasValue ?
                new ObjectParameter("TrangThaiBaoHanh", trangThaiBaoHanh) :
                new ObjectParameter("TrangThaiBaoHanh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatTrangThaiBaoHanh", maPhieuBHParameter, trangThaiYeuCauBHParameter, trangThaiBaoHanhParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_HienThiBaoHanh_Result> sp_HienThiBaoHanh(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiBaoHanh_Result>("sp_HienThiBaoHanh", maKHParameter);
        }
    
        public virtual ObjectResult<sp_HienThiBaoHanhTheoMaBH_Result> sp_HienThiBaoHanhTheoMaBH(Nullable<int> maBH)
        {
            var maBHParameter = maBH.HasValue ?
                new ObjectParameter("MaBH", maBH) :
                new ObjectParameter("MaBH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiBaoHanhTheoMaBH_Result>("sp_HienThiBaoHanhTheoMaBH", maBHParameter);
        }
    
        public virtual ObjectResult<sp_HienThiHuyDH_Result> sp_HienThiHuyDH(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiHuyDH_Result>("sp_HienThiHuyDH", maKHParameter);
        }
    
        public virtual ObjectResult<sp_HienThiYeuCauBHTheoMaKH_Result> sp_HienThiYeuCauBHTheoMaKH(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiYeuCauBHTheoMaKH_Result>("sp_HienThiYeuCauBHTheoMaKH", maKHParameter);
        }
    
        public virtual ObjectResult<sp_HienThiYeuCauBHTheoTrangThai_Result> sp_HienThiYeuCauBHTheoTrangThai(Nullable<int> trangThai)
        {
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HienThiYeuCauBHTheoTrangThai_Result>("sp_HienThiYeuCauBHTheoTrangThai", trangThaiParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_TaoYeuCauBH(Nullable<int> maBH, string lyDo)
        {
            var maBHParameter = maBH.HasValue ?
                new ObjectParameter("MaBH", maBH) :
                new ObjectParameter("MaBH", typeof(int));
    
            var lyDoParameter = lyDo != null ?
                new ObjectParameter("LyDo", lyDo) :
                new ObjectParameter("LyDo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoYeuCauBH", maBHParameter, lyDoParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<ThongKeHDTheoKhoang_Result> ThongKeHDTheoKhoang(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, Nullable<int> trangThai)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeHDTheoKhoang_Result>("ThongKeHDTheoKhoang", ngayBatDauParameter, ngayKetThucParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThongKeHoaDonTheoNam_Result> ThongKeHoaDonTheoNam(Nullable<int> nam, Nullable<int> trangThai)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeHoaDonTheoNam_Result>("ThongKeHoaDonTheoNam", namParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThongKeHoaDonTheoNgay_Result> ThongKeHoaDonTheoNgay(Nullable<int> ngay, Nullable<int> thang, Nullable<int> nam, Nullable<int> trangThai)
        {
            var ngayParameter = ngay.HasValue ?
                new ObjectParameter("Ngay", ngay) :
                new ObjectParameter("Ngay", typeof(int));
    
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeHoaDonTheoNgay_Result>("ThongKeHoaDonTheoNgay", ngayParameter, thangParameter, namParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThongKeHoaDonTheoThang_Result> ThongKeHoaDonTheoThang(Nullable<int> thang, Nullable<int> nam, Nullable<int> trangThai)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeHoaDonTheoThang_Result>("ThongKeHoaDonTheoThang", thangParameter, namParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<ThongKeNam_Result> ThongKeNam(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNam_Result>("ThongKeNam", yearParameter);
        }
    
        public virtual ObjectResult<ThongKeThang_Result> ThongKeThang(Nullable<int> year, Nullable<int> month)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeThang_Result>("ThongKeThang", yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<ThongKeTuan_Result> ThongKeTuan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTuan_Result>("ThongKeTuan");
        }
    
        public virtual int UpdateCartItemQuantity(Nullable<int> customerId, Nullable<int> productId, Nullable<int> newQuantity)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var newQuantityParameter = newQuantity.HasValue ?
                new ObjectParameter("NewQuantity", newQuantity) :
                new ObjectParameter("NewQuantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCartItemQuantity", customerIdParameter, productIdParameter, newQuantityParameter);
        }
    
        public virtual int UpdateTrangThaiHoanHang(Nullable<int> maHoanHang, Nullable<int> trangThai)
        {
            var maHoanHangParameter = maHoanHang.HasValue ?
                new ObjectParameter("MaHoanHang", maHoanHang) :
                new ObjectParameter("MaHoanHang", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTrangThaiHoanHang", maHoanHangParameter, trangThaiParameter);
        }
    
        public virtual int XoaGioHang(Nullable<int> customerId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaGioHang", customerIdParameter);
        }
    }
}
