//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SanPham
    {
        public SanPham()
        {
            this.BaoHanhs = new HashSet<BaoHanh>();
            this.CTDDHs = new HashSet<CTDDH>();
            this.CTGioHangs = new HashSet<CTGioHang>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
            this.YeuCauBHs = new HashSet<YeuCauBH>();
        }

        public int MaSP { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        public string TenSP { get; set; }
        
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> UuDai { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        [AllowHtml]
        public string MoTa { get; set; }
        [AllowHtml]
        public string ThongSoKyThuat { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        public string ChinhSachBaoHanh { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        public Nullable<int> ThoiGianBaoHanh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> TrangThai { get; set; }
        
        public Nullable<int> MaHinhAnh { get; set; }
        
        public Nullable<int> MaDanhMuc { get; set; }
        
        public Nullable<int> MaHang { get; set; }
        public Nullable<int> SoLuongDaBanRa { get; set; }
        [Required(ErrorMessage = "Không được để trống !")]
        public Nullable<decimal> GiaGoc { get; set; }

        public virtual ICollection<BaoHanh> BaoHanhs { get; set; }
        public virtual ICollection<CTDDH> CTDDHs { get; set; }
        public virtual ICollection<CTGioHang> CTGioHangs { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual HinhAnh HinhAnh { get; set; }
        public virtual ICollection<YeuCauBH> YeuCauBHs { get; set; }
    }
}





