//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThietBiDienTu.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauBH
    {
        public int MaPhieuBH { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaBH { get; set; }
        public Nullable<System.DateTime> NgayYeuCau { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual BaoHanh BaoHanh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
